
version: '3.6'
services:

services:

   producer:
      container_name: producer
      build: .      
      image: wanderlust
      command: python producer.py data/traces/nyc.gpx
      working_dir: /wl/producer
      volumes:
         - .:/wl
