
version: '3.6'

services:

   zookeeper:
      container_name: zookeeper
      image: confluentinc/cp-zookeeper
      environment:
         - ZOOKEEPER_CLIENT_PORT=2181
         - ZOOKEEPER_TICK_TIME=2000
      ports:
         - 2181:2181    # ZOOKEEPER_CLIENT_PORT

   kafka:
      container_name: kafka
      image: confluentinc/cp-kafka
      environment:
         - ALLOW_PLAINTEXT_LISTENER=yes
         - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.2.105:9092
         - KAFKA_BROKER_ID=1
         - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
         - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      ports:
         - 9092:9092    # KAFKA_CLIENT_PORT  
      depends_on:
         - zookeeper      
